### ISSUE TITLE
Add SASS support

### ISSUE THREAD

**Issue by carryall** [nimblehq/react-templates#10]
## Why

Add [node-sass](https://github.com/sass/node-sass) oackage to support SASS

## Who Benefits?

React app developers
 
## Acceptance criteria

After creating a React app using the template, the developer should be able to use SASS for styling instead of CSS

**Comment by rafayet-monon** [comment]
@carryall Should we add [scss-lint](https://github.com/sds/scss-lint) in the scope of this issue?
