### ISSUE TITLE
Add absolute import functionality

### ISSUE THREAD

**Issue by rafayet-monon** [nimblehq/react-templates#22]
## Why

Instead of using the root path from the current path absolute import can make look imports much more readable. Absolute imports use the `src` folder as root path.

- Existing import - `import * from '../../abc/d.js'` 
- Absolute import - `import * from 'abc/d.js'` 

Resource: https://medium.com/hackernoon/absolute-imports-with-create-react-app-4c6cfb66c35d

## Who Benefits?

React app developers

**Comment by malparty** [comment]
Has been implemented (cf `gutakk` reference in Jun 4 2021).
