### ISSUE TITLE
Fix: README completeness and typos

### ISSUE THREAD

**Issue by olivierobert** [nimblehq/react-templates#25]
## Issue

When reviewing the README, I found the following issues:
- No Node version prerequisites
- No link to the NPM package: https://www.npmjs.com/package/cra-template-nimble
- Typo
 
![image](https://user-images.githubusercontent.com/696529/120162306-73a80580-c222-11eb-9f1f-4547ab814514.png)

## Expected

The README  package should contain as much information as possible and be typo-free. In terms of structure, https://github.com/nimblehq/elixir-templates can be followed.
 
## Steps to reproduce

Go to: https://github.com/nimblehq/react-templates

**Comment by gutakk** [comment]
**Update**
1. This template does not support Node below version 12 (After using version 10 to create the project)
2. When using Node version 15.1 this error occurs
<img width="714" alt="Screen Shot 2564-06-03 at 16 09 56" src="https://user-images.githubusercontent.com/29707647/120620520-3f814e80-c487-11eb-9e84-4e896b73abd0.png">

Finally, everything work fine when I using Node version 14.14

**Comment by malparty** [comment]
@gutakk I will indicate version 14.14 at the moment. But we will need to fix this... it's weird. Especially once setup, you can upgrade the node version to 16.X.X and all scripts will work fine :o
