### ISSUE TITLE
Update ESLint rules to make it consistent with our convention

### ISSUE THREAD

**Issue by carryall** [nimblehq/react-templates#43]
## Why

The current ESLint rules are not consistent with our [Javascript](https://nimblehq.co/compass/development/code-conventions/javascript/) and [React](https://nimblehq.co/compass/development/code-conventions/javascript/react/) conventions, for example:
- Limit each line of code to fewer than 130 characters.
- Use semicolons at the end of each statement.
- Use a trailing comma after each item in a multi-line array or object literal, including the last item.

## Who Benefits?

everyone

**Comment by malparty** [comment]
Should we consider moving on to a "format handled by prettier" & "only keep linter for code optimization" approach? 
Read more:
- [Prettier vs. Linters](https://prettier.io/docs/en/comparison.html) (from Prettier)
- [An article about possible conflict between ESLint and Prettier, and some solutions](https://dev.to/viniciuskneves/prettier-eslint-and-typescript-491j#:~:text=user%2Dguide/configuring/-,Prettier%20%2B%20ESLint,-There%20are%20a)

The main objective is to prevent conflicts between both ESLint and Prettier. 
A big advantage of Prettier is that it can format a file on save in a much seamless way that what ESLint can do.
