### ISSUE TITLE
Add Gitlab merge request templates

### ISSUE THREAD

**Issue by hoangmirs** [nimblehq/react-templates#50]
## Why

Since some projects required putting the source code on Gitlab, so having the Gitlab merge request templates should be added.
The templates can be referenced from here: https://github.com/nimblehq/varun-web/tree/develop/.gitlab/merge_request_templates
![_gitlab-ci_yml_—_varun-matchmaking-web](https://user-images.githubusercontent.com/7344405/160530241-18835da7-9407-4227-8221-3fa57d96dbb0.png)

## Who Benefits?

React developers who use Gitlab

**Comment by olivierobert** [comment]
How about adding these to https://github.com/nimblehq/git-template too? 💭

**Comment by hoangmirs** [comment]
> How about adding these to https://github.com/nimblehq/git-template too? 💭

I created an issue here: https://github.com/nimblehq/git-template/issues/22
