### ISSUE TITLE
Add the Github Actions build/deploy workflows

### ISSUE THREAD

**Issue by hoangmirs** [nimblehq/react-templates#51]
## Why

The template should have default build/deploy templates. This feature was added to other templates (rails, elixir, gin) to deploy to Heroku, so having it in this template is good as well. 

For the React application, we can use [Netlify](https://www.netlify.com/) to leverage the power of Netlify to deploy the application, and we also had the Netlify account already.

There is a simple action that we can use to build our own workflow: [Netlify Deploy](https://github.com/marketplace/actions/netlify-deploy)

Other alternatives: [Heroku](https://www.heroku.com/), [Vercel](https://vercel.com/)

We should create at least 2 workflows:
- Preview the build of a pull request
- Deploy to servers

## Who Benefits?
React developers

**Comment by malparty** [comment]
@hoangmirs should we have a poll to vote on which service should be supported (Netlify vs Heroku vs ...) ? :) 
Thanks!

**Comment by hoangmirs** [comment]
@malparty I've checked some information. Heroku is often used for backend applications, so it is okay, but it's not suitable for this case. Then we have Netlify and Vercel left (you guys can propose more).
There are some posts: [snipcart](https://snipcart.com/blog/vercel-vs-netlify), [dev.to](https://dev.to/maxniederman/netlify-vs-vercel-a-comparison-5643) that compare them you can check out.
But the important difference is Netlify allows commercial use but [Vercel does not](https://vercel.com/docs/concepts/limits/fair-use-policy#commercial-usage). Vercel will shut the site down when detecting the violation. Netlify does not mention this, but [some people confirmed it](https://dev.to/tonyketcham/comment/16kma)
