### ISSUE TITLE
Migrate from `@import` to `@use` and `@forward`

### ISSUE THREAD

**Issue by carryall** [nimblehq/react-templates#54]
## Why

As the [`@import` would be deprecated in a few years](https://sass-lang.com/documentation/at-rules/import) so we better migrate from `@import` to [`@use`](https://sass-lang.com/documentation/at-rules/use) and [`@forward`](https://sass-lang.com/documentation/at-rules/forward)
so instead of `@import 'variables';` we should `@forward 'variables';` then when working on the project we can `@use './varialbes';`

Note that this would depend on the [issue to replace `node-sass` with `dart-sass`](https://github.com/nimblehq/react-templates/issues/52) to be closed first

## Who Benefits?

everyone

**Comment by olivierobert** [comment]
Indeed, in addition to the deprecation, using `@use` and `@forward` allow for better namespacing of styles. However, do note that `dart-sass` is required as `node-sass` does not support this. [Here](https://dev.to/ibreakcodes/use-forward-in-sass-2bab) is a good recap of this topic.
