### ISSUE TITLE
Fix: Test failed when creating a new project

### ISSUE THREAD

**Issue by hoangmirs** [nimblehq/react-templates#63]
## Issue

- Created a new project from this template and run `npm run test`, this error occurred:
![mirs_Mirss-MacBook-Pro___Documents_Nimble_Projects_internal_test-dev](https://user-images.githubusercontent.com/7344405/161535125-691c94fa-8d09-46ad-9698-647bb6163b52.png)

- Similar issue: https://github.com/facebook/create-react-app/issues/11792

## Expected

`npm run test` should be run properly

## Steps to reproduce

1. Create a new project
2. Run `npm run test` and observe the result

**Comment by malparty** [comment]
@hoangmirs shouldn't you run `yarn test` instead? 🤔

**Comment by malparty** [comment]
(we are investigating, it seems a Node version issue)
