### ISSUE TITLE
[RFC] Support only one package manager or keep both?

### ISSUE THREAD

**Issue by malparty** [nimblehq/react-templates#66]
## Why

While working on the GitHub Actions, I realize that we need to define inside these actions if we use `yarn` or `npm`. 
This is a source of confusion for a new user of the template, who might create and manage the application with `yarn` but the tests will run using `npm` (thus having no `package.lock` available and at risk of using different dependencies).

## Poll

**Update: Poll replaced by a static picture** — the vote continue [below](https://github.com/nimblehq/react-templates/issues/66#issuecomment-1091071601)
![image](https://user-images.githubusercontent.com/77609814/162121418-4660a96e-0b04-4369-9c5e-6d347de58af8.png)

## Who Benefits?

- Developers — won't need to adjust the GitHub actions.
- Template contributors — no need to test both package manager each time

**Comment by malparty** [comment]
As of today, the results seem more on the side of `yarn`. 
I will wait until tomorrow to confirm this. Then I will review the README.md and workflow (the test workflow is using `npm`) to be `yarn only`. 

![image](https://user-images.githubusercontent.com/77609814/161890295-f7c1c671-333a-4469-a935-4a39e01deb0d.png)

**Comment by hoangmirs** [comment]
I voted for npm:
- npm is shipped with Node.js, we don't need to install any extra packages.
- npm is better than before, the speed was improved from npm 5.0.

**Comment by malparty** [comment]
The initial poll made it clear that we do not want to support "both npm and yarn simultaneously", but it is not clear who prefers npm versus who prefers yarn, versus who is fine with any of these options (as long as we don't need to support both). 

here is a second poll to ensure we take a decision that best reflect the need/wish of our teammates:

[![](https://api.gh-polls.com/poll/01G014T4HVDR960NGESDE3VKQH/only%20npm)](https://api.gh-polls.com/poll/01G014T4HVDR960NGESDE3VKQH/only%20npm/vote)
[![](https://api.gh-polls.com/poll/01G014T4HVDR960NGESDE3VKQH/only%20yarn)](https://api.gh-polls.com/poll/01G014T4HVDR960NGESDE3VKQH/only%20yarn/vote)
[![](https://api.gh-polls.com/poll/01G014T4HVDR960NGESDE3VKQH/either%20npm%20or%20yarn%2C%20but%20not%20both)](https://api.gh-polls.com/poll/01G014T4HVDR960NGESDE3VKQH/either%20npm%20or%20yarn%2C%20but%20not%20both/vote)


![image](https://user-images.githubusercontent.com/77609814/162121216-0fa27947-c106-4e57-8562-1e9f03e3032a.png)
