### ISSUE TITLE
Add a GitHub Action for displaying Jest test coverage information in pull requests

### ISSUE THREAD

**Issue by malparty** [nimblehq/react-templates#69]
## Why

Test coverage information helps us know where our code is not tested. Having it visible in Pull Requests enforces a higher level of test coverage or at least opens a discussion on why a part is not covered.

## Who Benefits?

Code Reviewers with time saved in reviewing the test coverage.
Application quality with test coverage being more often checked and discussed.

**Comment by olivierobert** [comment]
Thanks for this submission. This aligns with [this objective](https://www.notion.so/nimblehq/Standardize-test-driven-development-in-web-and-mobile-client-applications-ba0bbc869c9c4e4da69c0eaec0ac6b65) on the engineering roadmap. Add testing coverage to PRs is an efficient way to ensure tests are continuously written and improved.

Note that [Danger](https://danger.systems/) is our go-to tool to annotate PRs across all chapters. So we should adopt it also for the JS stack and thus we could use https://danger.systems/js/plugins/danger-plugin-jest-codecov.html

**Comment by carryall** [comment]
Closed as the PR #70 is already merged
